@hostname = localhost
@port = 3003
@baseUrl = {{hostname}}:{{port}}
@blogs = api/blogs
@users = api/users
@login = api/login
@contentType = application/json

###

GET http://{{baseUrl}}/{{blogs}}

###

# @name newBlog
POST http://{{baseUrl}}/{{blogs}}
Content-Type: {{contentType}}

{
  "title": "Joel On Software", 
  "author": "Joel Spolsky",
  "url": "https://www.joelonsoftware.com/",
  "likes": 0
}

###

PUT http://{{baseUrl}}/{{blogs}}/{{newBlog.response.body.id}}
Content-Type: {{contentType}}

{
  "title": "Joel On Software", 
  "author": "Joel Spolsky",
  "url": "https://www.joelonsoftware.com/",
  "likes": 5
}

###

DELETE http://{{baseUrl}}/{{blogs}}/{{newBlog.response.body.id}}

###

GET http://{{baseUrl}}/{{users}}

###

POST http://{{baseUrl}}/{{users}}
Content-Type: {{contentType}}

{
  "username": "tommy", 
  "name": "Thomas Bailey",
  "password": "p@ssW04D"
}

###

# @name loginUser

POST http://{{baseUrl}}/{{login}}
Content-Type: {{contentType}}

{
  "username": "tommy",
  "password": "p@ssW04D"
}