GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Joel On Software", 
  "author": "Joel Spolsky",
  "url": "https://www.joelonsoftware.com/",
  "likes": 0
}

###

DELETE http://localhost:3003/api/blogs/5d5bdf9901242208c8884c56