@hostname = localhost
@port = 3003

@apiPath = /api/blogs
@baseUrl = {{hostname}}:{{port}}{{apiPath}}
@contentType = application/json

###

GET http://{{baseUrl}}

###

# @name newBlog
POST http://{{baseUrl}}
Content-Type: {{contentType}}

{
  "title": "Joel On Software", 
  "author": "Joel Spolsky",
  "url": "https://www.joelonsoftware.com/",
  "likes": 0
}

###

PUT http://{{baseUrl}}/{{newBlog.response.body.id}}
Content-Type: {{contentType}}

{
  "title": "Joel On Software", 
  "author": "Joel Spolsky",
  "url": "https://www.joelonsoftware.com/",
  "likes": 5
}

###

DELETE http://{{baseUrl}}/{{newBlog.response.body.id}}